repos:
  # Markdown plus
  - repo: https://github.com/icampus-wildau/markdown-plus
    rev: 0.1.4
    hooks:
      - id: mdplus-parse

  # Batch of helpful formatters and patterns
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: "v4.6.0"
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-docstring-first
      - id: debug-statements
      - id: mixed-line-ending

  # Adds a standard feel to import segments
  - repo: https://github.com/pycqa/isort
    rev: 5.13.2
    hooks:
      - id: isort
        args:
          - "--force-single-line-imports"
          # - "--add-import"
          # - "from __future__ import annotations"
          - "--profile"
          - "black"

  # Format code. No, I don't like everything black does either.
  - repo: https://github.com/psf/black-pre-commit-mirror
    rev: 24.4.1
    hooks:
      - id: black
        args: ["--line-length", "120"]

  # Add a license header to all source files.
  - repo: https://github.com/Lucas-C/pre-commit-hooks
    rev: v1.5.5
    hooks:
      - id: insert-license
        files: \.(msg|py|srv)$
        args:
          - --use-current-year
          - --license-filepath
          - docs/LICENSE.txt
          - --comment-style
          - "#"

      - id: insert-license
        files: \.(ino)$
        args:
          - --use-current-year
          - --license-filepath
          - docs/LICENSE.txt
          - --comment-style
          - "//"
